# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_Nasa_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1106, 983)
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.displayWindow = QtWidgets.QFrame(self.centralwidget)
        self.displayWindow.setStyleSheet("background-color: rgb(54, 54, 54)")
        self.displayWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.displayWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.displayWindow.setObjectName("displayWindow")
        self.gridLayout = QtWidgets.QGridLayout(self.displayWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.mic8signal = QtWidgets.QFrame(self.displayWindow)
        self.mic8signal.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.mic8signal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mic8signal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mic8signal.setObjectName("mic8signal")
        self.gridLayout.addWidget(self.mic8signal, 2, 8, 1, 1)
        self.microphone4 = QtWidgets.QFrame(self.displayWindow)
        self.microphone4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.microphone4.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.microphone4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.microphone4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.microphone4.setObjectName("microphone4")
        self.M4 = QtWidgets.QTextBrowser(self.microphone4)
        self.M4.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.M4.setObjectName("M4")
        self.gridLayout.addWidget(self.microphone4, 3, 4, 1, 1)
        self.microphone8 = QtWidgets.QFrame(self.displayWindow)
        self.microphone8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.microphone8.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.microphone8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.microphone8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.microphone8.setObjectName("microphone8")
        self.M8 = QtWidgets.QTextBrowser(self.microphone8)
        self.M8.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.M8.setObjectName("M8")
        self.gridLayout.addWidget(self.microphone8, 3, 8, 1, 1)
        self.microphone6 = QtWidgets.QFrame(self.displayWindow)
        self.microphone6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.microphone6.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.microphone6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.microphone6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.microphone6.setObjectName("microphone6")
        self.M6 = QtWidgets.QTextBrowser(self.microphone6)
        self.M6.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.M6.setObjectName("M6")
        self.gridLayout.addWidget(self.microphone6, 3, 6, 1, 1)
        self.microphone5 = QtWidgets.QFrame(self.displayWindow)
        self.microphone5.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.microphone5.setObjectName("microphone5")
        self.M5 = QtWidgets.QTextBrowser(self.microphone5)
        self.M5.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.M5.setObjectName("M5")
        self.gridLayout.addWidget(self.microphone5, 3, 5, 1, 1)
        self.microphone2 = QtWidgets.QFrame(self.displayWindow)
        self.microphone2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.microphone2.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.microphone2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.microphone2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.microphone2.setObjectName("microphone2")
        self.M2 = QtWidgets.QTextBrowser(self.microphone2)
        self.M2.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.M2.setObjectName("M2")
        self.gridLayout.addWidget(self.microphone2, 3, 2, 1, 1)
        self.voiceToggleStatus = QtWidgets.QFrame(self.displayWindow)
        self.voiceToggleStatus.setMaximumSize(QtCore.QSize(16777215, 75))
        self.voiceToggleStatus.setStyleSheet("background-color:rgb(255, 253, 175)")
        self.voiceToggleStatus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.voiceToggleStatus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.voiceToggleStatus.setObjectName("voiceToggleStatus")
        self.VoiceToggleActive = QtWidgets.QTextBrowser(self.voiceToggleStatus)
        self.VoiceToggleActive.setGeometry(QtCore.QRect(0, 0, 471, 81))
        self.VoiceToggleActive.setObjectName("VoiceToggleActive")
        self.gridLayout.addWidget(self.voiceToggleStatus, 1, 5, 1, 4)
        self.voltage = QtWidgets.QFrame(self.displayWindow)
        self.voltage.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.voltage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.voltage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.voltage.setObjectName("voltage")
        self.Voltage = QtWidgets.QTextBrowser(self.voltage)
        self.Voltage.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.Voltage.setObjectName("Voltage")
        self.gridLayout.addWidget(self.voltage, 3, 0, 1, 1)
        self.systemStatus = QtWidgets.QFrame(self.displayWindow)
        self.systemStatus.setMaximumSize(QtCore.QSize(16777215, 75))
        self.systemStatus.setStyleSheet("background-color:rgb(173, 255, 167)")
        self.systemStatus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.systemStatus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.systemStatus.setObjectName("systemStatus")
        self.SystemOperational = QtWidgets.QTextBrowser(self.systemStatus)
        self.SystemOperational.setGeometry(QtCore.QRect(0, 0, 591, 81))
        self.SystemOperational.setObjectName("SystemOperational")
        self.gridLayout.addWidget(self.systemStatus, 1, 0, 1, 5)
        self.microphone3 = QtWidgets.QFrame(self.displayWindow)
        self.microphone3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.microphone3.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.microphone3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.microphone3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.microphone3.setObjectName("microphone3")
        self.M3 = QtWidgets.QTextBrowser(self.microphone3)
        self.M3.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.M3.setObjectName("M3")
        self.gridLayout.addWidget(self.microphone3, 3, 3, 1, 1)
        self.microphone1 = QtWidgets.QFrame(self.displayWindow)
        self.microphone1.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.microphone1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.microphone1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.microphone1.setObjectName("microphone1")
        self.M1 = QtWidgets.QTextBrowser(self.microphone1)
        self.M1.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.M1.setObjectName("M1")
        self.gridLayout.addWidget(self.microphone1, 3, 1, 1, 1)
        self.microphone7 = QtWidgets.QFrame(self.displayWindow)
        self.microphone7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.microphone7.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.microphone7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.microphone7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.microphone7.setObjectName("microphone7")
        self.M7 = QtWidgets.QTextBrowser(self.microphone7)
        self.M7.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.M7.setObjectName("M7")
        self.gridLayout.addWidget(self.microphone7, 3, 7, 1, 1)
        self.Localization = QtWidgets.QFrame(self.displayWindow)
        self.Localization.setStyleSheet("background-color: rgb(138, 199, 255)")
        self.Localization.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Localization.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Localization.setObjectName("Localization")
        self.SoundLocalization = QtWidgets.QTextBrowser(self.Localization)
        self.SoundLocalization.setGeometry(QtCore.QRect(350, 0, 381, 81))
        self.SoundLocalization.setObjectName("SoundLocalization")
        self.gridLayout.addWidget(self.Localization, 0, 0, 1, 9)
        self.voltageIntensity = QtWidgets.QFrame(self.displayWindow)
        self.voltageIntensity.setMaximumSize(QtCore.QSize(16777215, 150))
        self.voltageIntensity.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.voltageIntensity.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.voltageIntensity.setFrameShadow(QtWidgets.QFrame.Raised)
        self.voltageIntensity.setObjectName("voltageIntensity")
        self.gridLayout.addWidget(self.voltageIntensity, 2, 0, 1, 1)
        self.mic1signal = QtWidgets.QFrame(self.displayWindow)
        self.mic1signal.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.mic1signal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mic1signal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mic1signal.setObjectName("mic1signal")
        self.gridLayout.addWidget(self.mic1signal, 2, 1, 1, 1)
        self.mic2signal = QtWidgets.QFrame(self.displayWindow)
        self.mic2signal.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.mic2signal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mic2signal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mic2signal.setObjectName("mic2signal")
        self.gridLayout.addWidget(self.mic2signal, 2, 2, 1, 1)
        self.mic3signal = QtWidgets.QFrame(self.displayWindow)
        self.mic3signal.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.mic3signal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mic3signal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mic3signal.setObjectName("mic3signal")
        self.gridLayout.addWidget(self.mic3signal, 2, 3, 1, 1)
        self.mic4signal = QtWidgets.QFrame(self.displayWindow)
        self.mic4signal.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.mic4signal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mic4signal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mic4signal.setObjectName("mic4signal")
        self.gridLayout.addWidget(self.mic4signal, 2, 4, 1, 1)
        self.mic5signal = QtWidgets.QFrame(self.displayWindow)
        self.mic5signal.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.mic5signal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mic5signal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mic5signal.setObjectName("mic5signal")
        self.gridLayout.addWidget(self.mic5signal, 2, 5, 1, 1)
        self.mic6signal = QtWidgets.QFrame(self.displayWindow)
        self.mic6signal.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.mic6signal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mic6signal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mic6signal.setObjectName("mic6signal")
        self.gridLayout.addWidget(self.mic6signal, 2, 6, 1, 1)
        self.mic7signal = QtWidgets.QFrame(self.displayWindow)
        self.mic7signal.setStyleSheet("background-color: rgb(202, 212, 248)")
        self.mic7signal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mic7signal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mic7signal.setObjectName("mic7signal")
        self.gridLayout.addWidget(self.mic7signal, 2, 7, 1, 1)
        self.gridLayout_2.addWidget(self.displayWindow, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.M4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">M4</span></p></body></html>"))
        self.M8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">M8</span></p></body></html>"))
        self.M6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">M6</span></p></body></html>"))
        self.M5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">M5</span></p></body></html>"))
        self.M2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">M2</span></p></body></html>"))
        self.VoiceToggleActive.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">Voice Toggle Active</span></p></body></html>"))
        self.Voltage.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">V</span></p></body></html>"))
        self.SystemOperational.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">System Operational</span></p></body></html>"))
        self.M3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">M3</span></p></body></html>"))
        self.M1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">M1</span></p></body></html>"))
        self.M7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">M7</span></p></body></html>"))
        self.SoundLocalization.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">Sound Localization</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
